name: Run Matcha Contact Finder (Sheets API)

on:
  workflow_dispatch:
    inputs:
      start-row:
        description: 'Row number to start processing'
        required: false
        default: '1508'
      worksheet-name:
        description: 'Worksheet title'
        required: false
        default: '抹茶営業リスト（カフェ）'
  push:
    branches:
      - main

jobs:
  update:
    if: ${{ github.event_name != 'pull_request' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - run: pip install -r requirements.txt

      - name: Validate required secrets
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
          SPREADSHEET_ID: ${{ secrets.SPREADSHEET_ID }}
        run: |
          [ -n "$GOOGLE_CREDENTIALS" ] || { echo "Missing secret: GOOGLE_CREDENTIALS"; exit 1; }
          [ -n "$SPREADSHEET_ID" ] || { echo "Missing secret: SPREADSHEET_ID"; exit 1; }

      - name: Write and validate service account key
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        run: |
          printf '%s' "$GOOGLE_CREDENTIALS" > sa.json
          python -c "import json; json.load(open('sa.json','r',encoding='utf-8')); print('sa.json OK')"

      - name: Update contacts on Google Sheet
        env:
          SPREADSHEET_ID: ${{ secrets.SPREADSHEET_ID }}
        run: |
          python update_contact_info_api.py \
            --spreadsheet-id "$SPREADSHEET_ID" \
            --worksheet "${{ inputs['worksheet-name'] }}" \
            --start-row "${{ inputs['start-row'] }}"

  skip:
    if: ${{ github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "Skipping contact finder on pull_request events"
