name: Run Matcha Contact Finder (Sheets API)

on:
  workflow_dispatch:
    inputs:
      start-row:
        description: 'Row number to start processing'
        required: false
        default: '1508'
      worksheet-name:
        description: 'Worksheet title'
        required: false
        default: '抹茶営業リスト（カフェ）'
  push:
    branches:
      - main

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - run: pip install -r requirements.txt
 
      - name: Resolve credentials and spreadsheet id
        id: resolve
        env:
          RAW_SECRET: ${{ secrets.GOOGLE_CREDENTIALS }}
          RAW_VAR: ${{ vars.GOOGLE_CREDENTIALS }}
          B64_SECRET: ${{ secrets.GOOGLE_CREDENTIALS_B64 }}
          B64_VAR: ${{ vars.GOOGLE_CREDENTIALS_B64 }}
          SID_SECRET: ${{ secrets.SPREADSHEET_ID }}
          SID_VAR: ${{ vars.SPREADSHEET_ID }}
        run: |
          set -euo pipefail
          SPREADSHEET_ID="${SID_SECRET:-${SID_VAR:-}}"
          if [ -z "${SPREADSHEET_ID}" ]; then
            echo "ERROR: SPREADSHEET_ID is not set."; exit 1
          fi
          if [ -n "${RAW_SECRET}" ]; then
            printf '%s' "${RAW_SECRET}" > sa.json
          elif [ -n "${RAW_VAR}" ]; then
            printf '%s' "${RAW_VAR}" > sa.json
          elif [ -n "${B64_SECRET}" ]; then
            printf '%s' "${B64_SECRET}" | base64 -d > sa.json
          elif [ -n "${B64_VAR}" ]; then
            printf '%s' "${B64_VAR}" | base64 -d > sa.json
          else
            echo "ERROR: GOOGLE_CREDENTIALS not found in secrets/vars."; exit 1
          fi
          python - <<'PY'
import json; json.load(open('sa.json','r',encoding='utf-8')); print('sa.json OK')
PY
          echo "spreadsheet_id=${SPREADSHEET_ID}" >> "$GITHUB_OUTPUT"

      - name: Update contacts on Google Sheet
        env:
          SPREADSHEET_ID: ${{ steps.resolve.outputs.spreadsheet_id }}
        run: |
          python update_contact_info_api.py \
            --spreadsheet-id "$SPREADSHEET_ID" \
            --worksheet "${{ inputs['worksheet-name'] }}" \
            --start-row "${{ inputs['start-row'] }}"
